### ISSUE TITLE
Add option for Ausländeramt at Hbf?

### ISSUE THREAD

**Issue by ifeimi** [noworneverev/aachen-termin-bot#1]
Hi, thank you very much for the work! I'm just wondering if you would be interested in adding another bot for appointments at the Ausländeramt at Hbf? I guess it shouldn't be difficult? Just changing a few URLs.

**Comment by ifeimi** [comment]
The thing is I'm working at the university but not employed by the university so I can't go to superC :(

**Comment by noworneverev** [comment]
For hbf, use https://t.me/hbf_termin, it's live now.
